### ISSUE TITLE
[question] how to setup http authorisation via env vars in docker compose?

### ISSUE THREAD

**Issue by renanbr** [joeferner/redis-commander#213]
first of all, thanks for this project

I would like to configure the HTTP authorisation via docker compose file.
Is this possible?

**Comment by Adverbly** [comment]
I have been trying to do this as well! I couldn't find a way to do it with ENV vars, so am making a go at using the entrypoint with command line args. This successfully sets the HTTP auth, but it seems to mess up the hostname, so I am not getting "Redis error Error: connect ENOENT /:redis:6379:0". The compose I am using is version 1 and looks like:
```
redis:
  image: redis:latest
  restart: always
redis-commander:
  restart: always
  image: rediscommander/redis-commander:latest
  entrypoint: node /src/redis-commander/bin/redis-commander
  links:
    - redis:redis
  ports:
    - '8081:8081'
  command: ["--http-u", "admin", "--http-p", $REDIS_COMMANDER_PASSWORD, "--redis-host", "redis:redis:6379:0:"]
```
