### ISSUE TITLE
options.dbIndex vs options.db

### ISSUE THREAD

**Issue by djeeg** [joeferner/redis-commander#233]
Hi, there seems to be some iffyness when connecting to multiple redis databases on the same host like this:

```
  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis0:redis:7000:0,redis1:redis:7000:1,redis2:redis:7000:2
```
	  
The configuration seems to parse correctly:
	  
```
"default_connections": [
   {
	 "label":"redis0",
	 "host":"redis",
	 "port":"7000",
	 "password":"",
	 "dbIndex":0
   },
   {
	 "label":"redis1",
	 "host":"redis",
	 "port":"7000",
	 "password":"",
	 "dbIndex":1
   },
   {
	 "label":"redis2",
	 "host":"redis",
	 "port":"7000",
	 "password":"",
	 "dbIndex":2
   }
]
```

However I see the same database is connected 3 times in the logs:

> Redis Connection redis:7000 Using Redis DB #0
> Redis Connection redis:7000 Using Redis DB #0
> Redis Connection redis:7000 Using Redis DB #0

I am thinking that here:

https://github.com/joeferner/redis-commander/blob/master/bin/redis-commander.js#L223

It should be redisConnection.options.**dbIndex** rather than redisConnection.options.**db**

Also in the web left tree view, a similar issue, the serverinfo shows as [label (host:port:0)] always 0

I think that one is because this line:

https://github.com/joeferner/redis-commander/blob/master/lib/routes/apiv1.js#L96

Should again be:

redisConnection.options.**dbIndex** rather than redisConnection.options.**db**

Also in the tree view, the nodes for one instance are appearing under the incorrect instance, though I havent tracked it down in source yet. It may be related to this issue.
