### ISSUE TITLE
Import - 500 Internal Server Error

### ISSUE THREAD

**Issue by luxel** [joeferner/redis-commander#248]
When using "Import" menu to import any json data, it returns 500 Internal Server Error.

The stack trace printed in docker container logs as below:
```
redis-commander_1  | TypeError: Cannot read property 'host' of undefined
redis-commander_1  |     at /usr/lib/node_modules/redis-commander/lib/routes/tools.js:76:45
redis-commander_1  |     at callbacks (/usr/lib/node_modules/redis-commander/node_modules/express/lib/router/index.js:164:37)
redis-commander_1  |     at param (/usr/lib/node_modules/redis-commander/node_modules/express/lib/router/index.js:138:11)
redis-commander_1  |     at pass (/usr/lib/node_modules/redis-commander/node_modules/express/lib/router/index.js:145:5)
redis-commander_1  |     at Router._dispatch (/usr/lib/node_modules/redis-commander/node_modules/express/lib/router/index.js:173:5)
redis-commander_1  |     at Object.router [as handle] (/usr/lib/node_modules/redis-commander/node_modules/express/lib/router/index.js:33:10)
redis-commander_1  |     at next (/usr/lib/node_modules/redis-commander/node_modules/connect/lib/proto.js:174:15)
redis-commander_1  |     at Object.addConnectionsToRequest [as handle] (/usr/lib/node_modules/redis-commander/lib/app.js:148:10)
redis-commander_1  |     at next (/usr/lib/node_modules/redis-commander/node_modules/connect/lib/proto.js:174:15)
redis-commander_1  |     at Immediate.<anonymous> (/usr/lib/node_modules/redis-commander/node_modules/express-session/index.js:433:7)
redis-commander_1  |     at runCallback (timers.js:764:11)
redis-commander_1  |     at tryOnImmediate (timers.js:734:5)
redis-commander_1  |     at processImmediate (timers.js:716:5)
```

This is the docker-composer.yml I used:
```yml
version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis1
    ports:
       - "6379:6379"
    volumes:
      - ./conf/redistmp:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
```
