### ISSUE TITLE
Environment variable URL_PREFIX does not work.

### ISSUE THREAD

**Issue by offbeatful** [joeferner/redis-commander#257]
I use the following docker-compose file:

```yaml
  redis-ui:
    container_name: redis-ui    
    image: rediscommander/redis-commander:latest    
    restart: always
    user: root
    environment:
      - PORT=80
      - URL_PREFIX=redis
      - REDIS_HOSTS=redis
    ports:      
      - 80:80
 ```
When composed I try to access redis-commander at http://localhost/redis and get a blank page with 'Cannot GET /redis'. http://localhost - works fine.

Logs:
`
Creating custom redis-commander config.
Configuration:
{
  "sidebarWidth":250,
  "locked":false,
  "CLIHeight":50,
  "CLIOpen":false,
  "default_connections": [
      {
        "label":"default",
        "host":"redis",
        "port":"6379",
        "password":"",
        "dbIndex":0
      }
  ]
}
node /usr/bin/redis-commander --port 80 --url-prefix redis
No Save: true
listening on  0.0.0.0 : 80
Redis Connection redis:6379 Using Redis DB #0
`
I tried setting URL_PREFIX to /redis as well - same result.

Please advice.
