### ISSUE TITLE
Startup fails (on kubernetes)

### ISSUE THREAD

**Issue by elm-** [joeferner/redis-commander#267]
I'm getting the following error when running it on Kubernetes. The config looks correct to me, anyone has an idea how to check this further?

```
Creating custom redis-commander config.
Configuration:
    {
    "sidebarWidth":250,
    "locked":false,
    "CLIHeight":50,
    "CLIOpen":false,
    "default_connections": [
        {
            "label":"redis",
            "host":"redis",
            "port":"6379",
            "password":"",
            "dbIndex":0
        }
        ]
    }
node ./bin/redis-commander --redis-port tcp://10.47.248.71:6379
No Save: false
listening on  0.0.0.0 : 8081
net.js:1032
      throw new errors.RangeError('ERR_SOCKET_BAD_PORT', port);
      ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received NaN.
    at lookupAndConnect (net.js:1032:13)
    at Socket.connect (net.js:1001:5)
    at Object.connect (net.js:124:35)
    at /redis-commander/node_modules/ioredis/lib/connectors/connector.js:44:20
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

The config for it:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-commander
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: redis-commander
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: rediscommander/redis-commander:latest
        ports:
        - name: redis-commander
          containerPort: 8081
        env:
        - name: REDIS_HOSTS
          value: redis:redis:6379
```

**Comment by stevenaldinger** [comment]
I looked into it the best I could and was not able to reproduce. **However, you gave us enough context that I can tell you what's going on and hopefully help you hack a solution**.

TLDR:

**Try adding this to your k8s spec (explicitly setting REDIS_PORT to empty string)**. If you only have a single redis instance running you can _maybe_ get away with REDIS_PORT=6379 but setting that explicitly will break other things I believe. I wrote the original entrypoint.sh and redis commander was not compatible with both configuration files and command line args (to my knowledge) so I just generated the config with env vars to give flexibility. Someone else has altered it since and there are a lot of caveats I don't think they considered.

```
        env:
        - name: REDIS_HOSTS
           value: redis:redis:6379
        - name: REDIS_PORT
           value: ""
```

1. This is the minimal equivalent to what you're doing which works fine:
  - `docker run -it -e REDIS_HOSTS=redis:redis:6379 rediscommander/redis-commander:latest`
2. I also ran the exact config you supplied and it worked fine.

**The key to your mystery is that your logs show `node ./bin/redis-commander --redis-port tcp://10.47.248.71:6379`.** [This is the only line in the entrypoint.sh script](https://github.com/joeferner/redis-commander/blame/master/docker/entrypoint.sh#L135) that is able to cause that behavior, given you clearly don't have overrides in your k8s spec (that would screw with the entrypoint).

My command (try running this):
> $:- kubectl exec -it "$(kubectl get po -l app=airflow -l tier=redis-commander -o jsonpath='{.items[0].metadata.name}')" -- sh -c "env | grep REDIS_"

My output:
> REDIS_HOSTS=redis:redis:6379
What I think your output is going to show:
> REDIS_HOSTS=redis:redis:6379
> REDIS_PORT=tcp://10.47.248.71:6379

**And to try the theory backwards to prove that _would_ case the behavior...**

My command:
> $: docker run -it -e REDIS_HOSTS=redis:redis:6379 -e REDIS_PORT=tcp://10.47.248.71:6379 rediscommander/redis-commander:latest
Output:
```
Creating custom redis-commander config.
Configuration:
    {
    "sidebarWidth":250,
    "locked":false,
    "CLIHeight":50,
    "CLIOpen":false,
    "default_connections": [
        {
            "label":"redis",
            "host":"redis",
            "port":"6379",
            "password":"",
            "dbIndex":0
        }
        ]
    }
node ./bin/redis-commander --redis-port tcp://10.47.248.71:6379
No Save: false
listening on  0.0.0.0 : 8081
setUpConnection Redis error RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received NaN.
    at lookupAndConnect (net.js:1032:13)
    at Socket.connect (net.js:1001:5)
    at Object.connect (net.js:124:35)
    at /redis-commander/node_modules/ioredis/lib/connectors/connector.js:47:22
    at process._tickCallback (internal/process/next_tick.js:176:11)
```
