### ISSUE TITLE
Refreshing page requires re-login. Trying to add server returns "Unauthorized - Missing Token"

### ISSUE THREAD

**Issue by lsattem** [joeferner/redis-commander#292]
Errors in title. 
When I try to add a server via the interface a new page is opened that simply says "Unauthorized - Missing Token". And if i try to refresh the page it asks me to log in again.

Compose file:

```
version: '3'
services:
    redis:
        container_name: redis
        hostname: redis
        image: redis

  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOST=local:redis:6379
          - HTTP_USER=test
          - HTTP_PASSWORD=test
      ports:
          - "8081:8081"
```
