### ISSUE TITLE
Error: connect EConnrefused

### ISSUE THREAD

**Issue by raupie** [joeferner/redis-commander#327]
I'm trying to use redis and redis-commander this way through docker-composer.

```
    redis:
        image: 'redis:latest'
        depends_on:
            - engine
    redisadmin:
        image: 'rediscommander/redis-commander:latest'
        environment:
            - 'REDIS_HOSTS=local:redis:6379'
        ports:
            - '8081:8081'
```
In the GUI nothing is connecting and in my logs I'm seeing this over and over again.

```
redisadmin_1   | setUpConnection Redis error Error: connect ECONNREFUSED 127.0.0.1:6379
redisadmin_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

**Comment by raupie** [comment]
Looks like my environment variable needed updated. 
```
redisadmin:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOST=redis
```
