### ISSUE TITLE
Cannot connect to different port using docker-compose.yml

### ISSUE THREAD

**Issue by nidkil** [joeferner/redis-commander#353]
Hi,

After changing the port using the provided `docker-compose.yml` redis-commander cannot connect. Error:

```
setUpConnection Redis error Error: connect ECONNREFUSED 172.19.0.2:6380
```

This is the changed `docker-compose.yml` file:

```
version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    ports:
      - "6380:6379"
    expose:
      - "6380"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8082:8081"
volumes:
  redis-data: {}
```

If I change the port back to `6379` in the `docker-compose.yml` then it works.

I can connect to Redis using the following node code:

```
import redis from 'redis'

const config = {
  host: '127.0.0.1',
  port: 6380,
  no_ready_check: true
}

const client = redis.createClient(config.port, config.host)

client.set('expireName', 'nidkil', (err, reply) => {
  if (err) {
    console.error('Error occurred:', err)
  } else {
    console.log('Response:', reply)
  }
})
```

Any ideas how I can make redis-commander connect to the changed Redis port?

**Comment by sseide** [comment]
what the output of redis-commander console log?
Is there another container named "redis" running?

**Comment by sseide** [comment]
and is the ip of the log message the same for `docker inspect redis`? Same exported port and ip as your error message states?

**Comment by nidkil** [comment]
> what the output of redis-commander console log?

```
bd67f695f300_redis-commander | Creating custom redis-commander config '/redis-commander/config/local-production.json'.
bd67f695f300_redis-commander | node ./bin/redis-commander
bd67f695f300_redis-commander | No Save: false
bd67f695f300_redis-commander | listening on  0.0.0.0 : 8081
bd67f695f300_redis-commander | setUpConnection Redis error Error: connect ECONNREFUSED 172.19.0.2:6380
bd67f695f300_redis-commander |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

> Is there another container named "redis" running?

There is only one container with the name `redis`. As far as I know container names must be unique, as they act as an identifier.

**Comment by nidkil** [comment]
> 
> 
> and is the ip of the log message the same for `docker inspect redis`? Same exported port and ip as your error message states?


```
"NetworkSettings": {                                                                           
    "Bridge": "",                                                                              
    "SandboxID": "d641687e05247e2b42ca890986ea25bcb3a90a6cefaf36af5424883b0aa66391",           
    "HairpinMode": false,                                                                      
    "LinkLocalIPv6Address": "",                                                                
    "LinkLocalIPv6PrefixLen": 0,                                                               
    "Ports": {                                                                                 
        "6379/tcp": [                                                                          
            {                                                                                  
                "HostIp": "0.0.0.0",                                                           
                "HostPort": "6380"                                                             
            }                                                                                  
        ],                                                                                     
        "6380/tcp": null                                                                       
    },                                                                                         
    "SandboxKey": "/var/run/docker/netns/d641687e0524",                                        
    "SecondaryIPAddresses": null,                                                              
    "SecondaryIPv6Addresses": null,                                                            
    "EndpointID": "",                                                                          
    "Gateway": "",                                                                             
    "GlobalIPv6Address": "",                                                                   
    "GlobalIPv6PrefixLen": 0,                                                                  
    "IPAddress": "",                                                                           
    "IPPrefixLen": 0,                                                                          
    "IPv6Gateway": "",                                                                         
    "MacAddress": "",                                                                          
    "Networks": {                                                                              
        "fwrd-queue_default": {                                                                
            "IPAMConfig": null,                                                                
            "Links": null,                                                                     
            "Aliases": [                                                                       
                "redis",                                                                       
                "eed9457059bf"                                                                 
            ],                                                                                 
            "NetworkID": "791477e3648ea059298634b7cf70b160a2516c51193bb675726f47dacb9846ba",   
            "EndpointID": "917252f90f05fdab8675d4ca4a503befa46635eb9d9dbbe3f035b67839fd052b",  
            "Gateway": "172.19.0.1",                                                           
            "IPAddress": "172.19.0.2",                                                         
            "IPPrefixLen": 16,                                                                 
            "IPv6Gateway": "",                                                                 
            "GlobalIPv6Address": "",                                                           
            "GlobalIPv6PrefixLen": 0,                                                          
            "MacAddress": "02:42:ac:13:00:02",                                                 
            "DriverOpts": null                                                                 
        }                                                                                      
    }                                                                                          
}
```

**Comment by nidkil** [comment]
I figured out what the problem is. I needed to change the port Redis is running on as well as the exposed port. This is the working Docker Compose file.

```
version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    entrypoint: /sbin/entrypoint.sh -- --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8082:8081"
volumes:
  redis-data: {}
```
