### ISSUE TITLE
Running RC as a service in a docker stack

### ISSUE THREAD

**Issue by Daemach** [joeferner/redis-commander#373]
I've created a docker environment variable called REDIS_HOSTS pointing to swarm:redis:6379 and set up the service  as below, but RC is trying to connect to localhost rather than the redis service.  What am I missing?

```
  redis:
    image: redis:latest
    networks:
      - thcg
    command: ["redis-server", "--appendonly", "yes"]
    volumes:    
      - redis:/data
    ports: 
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-commander:
    image: rediscommander/redis-commander:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - "8181:8081"
```

**Comment by funkyfisch** [comment]
There is a network defined for redis, called thcg. have you tried with "thcg:redis:6379" instead?

**Comment by Daemach** [comment]
Just tried that, no luck.  I added the thcg network to redis-commander too.

**Comment by sseide** [comment]
as i'm not into swarm...

Can you attach to the redis commander container (as root user) and try to ping around to find the correct name of the redis server host as seen from this container?

something along `docker exec -it redis-commander /bin/sh` and than `ping redis` inside container?

The "dns name" working from inside the redis commander container should go into REDIS_HOSTS as host name then.

Another note - as your config example does not mention the REDIS_HOSTS env anywhere - please check if this env-var is really set inside the container after attaching to it (`printenv`).

**Comment by sseide** [comment]
.. And if env var REDIS_HOSTS is set, the startup script creates a config file `/redis-commander/config/local-production.json` containing the data from env var converted to json config. Just check if this file exists and has everything as expected.

**Comment by Daemach** [comment]
I can create the connection manually after RC starts up.  It acts like it doesn't see the env variable, but this is the only way I know how to create an env variable in a stack - I use portainer to manage the swarm.  My other containers see the env=production var.

https://www.screencast.com/t/z8h07HNE

https://www.screencast.com/t/MrgHjyiR8yk

**Comment by sseide** [comment]
As your service file has the docker-compose format it should be possible to set environment variables for each container independently via "env_file" or "environment" (see https://docs.docker.com/compose/compose-file/#env_file)

example:
```
...
redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - "8181:8081"
```
This way you can defined them directly for RC. For passwords the `secrets` (or  `env_file`) keys of docker-compose may help.
