### ISSUE TITLE
SENTINEL_NAME not set by default

### ISSUE THREAD

**Issue by daniego** [joeferner/redis-commander#381]
I'm deploying in a kubernetes environment and noticed that SENTINEL_NAME is not set by default when using SENTINELS

**Comment by sseide** [comment]
cannot repoduce. If sentinel name param or env var is not set its using the default `mymaster` name as use per default on redis side.

What did you do exaclty or whats the expected outcome and what happened instead?

**Comment by daniego** [comment]
This is the k8s manifest
```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        imagePullPolicy: Always
        ports:
        - name: commander
          containerPort: 8081
        env:
        - name: SENTINELS
          value: "redis-ha.namespace.svc.cluster.local:26379"
```
and this the error logs from the container
```
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --sentinels redis-ha.namespace.svc.cluster.local:26379
Using scan instead of keys
/redis-commander/lib/util.js:456
      if (element.name.toLowerCase() === object.sentinelName.toLowerCase()) {
                                                             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at _isSameConnection (/redis-commander/lib/util.js:456:62)
    at /redis-commander/lib/util.js:412:12
    at Array.some (<anonymous>)
    at Object.containsConnection (/redis-commander/lib/util.js:411:22)
    at /redis-commander/bin/redis-commander.js:509:20
    at Array.forEach (<anonymous>)
    at startDefaultConnections (/redis-commander/bin/redis-commander.js:508:17)
    at startAllConnections (/redis-commander/bin/redis-commander.js:484:3)
    at Object.<anonymous> (/redis-commander/bin/redis-commander.js:293:5)
    at Module._compile (module.js:653:30)
```

By adding
```
        env:
        - name: SENTINEL_NAME
          value: "mymaster"
```
then the pod starts properly
