### ISSUE TITLE
Multiple Hosts with Docker Compose

### ISSUE THREAD

**Issue by thellimist** [joeferner/redis-commander#394]
How can this be achieved in a default way?

**Comment by sseide** [comment]
what do you want to archive? What does "multiple hosts" mean? What you are refering to?

**Comment by thellimist** [comment]
```
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379,local1:redis1:6379
    ports:
    - "8081:8081"
```

The code above connects to a two host. I'd like to connect to multiple hosts with saved configuration where the hosts have TLS.

**Comment by sseide** [comment]
using TLS its currently not possible to use the `REDIS_HOSTS` env var. As the readme states within the "Valid host strings" section you must create your own configuration file and define all configurations in there. Afterwards mount this file into the container. Do not set the `REDIS_HOSTS` env var within docker compose than!

Within your local docker compose directory create file `myconnections.json` with
```json
{
  "connections": [
    {
      "label": "first-db",
      "host": "redis",
      "port": 6379,
      "password": "pass-x",
      "dbIndex": 0,
      "tls": true
    },
    {
      "label": "second-db",
      "host": "redis1",
      "port": 6379,
      "password": "pass-y",
      "dbIndex": 0,
      "tls": true
    }
  ]
}
```
now mount this file into the container as `/redis-commander/config/local-production.json`
(Attention if docker engine is remote, the json config file must be referenced absolute and available one the remote docker host at this path!)
```yml
version: "3"
services:
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    volumes:
      - ./myconnections.json:/redis-commander/config/local-production.json
    ports:
      - "8081:8081"
```

Or - with newer docker compose versions and docker warm - you can create a config object from the json file and set this inside the container:

```yml
version: "3.3"
services:
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    configs:
      - source: my_connections
        target: /redis-commander/config/local-production.json
        uid: '100'
        gid: '0'
        mode: 0660
configs:
  my_connections:
    file: ./myconnections.json
```
