### ISSUE TITLE
When combined with Traefik, redis commander is checking for a token that doesn't exist.

### ISSUE THREAD

**Issue by jedarden** [joeferner/redis-commander#407]
I have a server. Domain.com

I use traefik v2 as a reverse proxy, which places rediscommander at Domain.com/redis

So theoretically, going to Domain.com/redis takes me to the login page. 

Instead, I'm presented with an error "Unauthorized - Missing Token"

Changing the routing in traefik so rediscommander is served at Domain.com works correctly. 

Looking at #292 suggests there's some sort of session validation going on. 

What other information can I provide to help?

**Comment by sseide** [comment]
We use Redis commander for some installs behind Traefik as Kubernetes Ingress and its working there with same setup (https://tools.domain.tld/commander).

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis-commander-ingress
  namespace: abc
  labels:
    traffic-type: proxy
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/ssl-proxy-headers: "X-Forwarded-Proto:https"
    ingress.kubernetes.io/custom-frame-options-value: SAMEORIGIN
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-preload: "true"
spec:
  rules:
  - host: tools.domain.tld
    http:
      paths:
      - backend:
          serviceName: redis-commander
          servicePort: 8081
        path: /commander

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis-commander
  namespace: abc
  name: redis-commander
spec:
  type: ClusterIP
  ports:
  - name: "redis-commander"
    port: 8081
  selector:
    stack: redis-commander

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: abc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-commander
  template:
    metadata:
      labels:
        io.kompose.service: redis-commander
        stack: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: redis-commander:dev
          env:
            - name: TRUST_PROXY
              value: '1'
            - name: K8S_SIGTERM
              value: '1'
            ... some more values here...
          ports:
            - containerPort: 8081

```

And inside the redis-commander json-config nothing special set - normal default values from docker image.
```
"server": {
    "address": "0.0.0.0",
    "port": 8081,
    "urlPrefix": "",
   ...
}
```
Hope it helps - as i said smiliar setup and it works. Please check the Traefik config, e.g. rule-type if its set correctly.

Best regards,
Stefan Seide

**Comment by sseide** [comment]
is it working now? can we close issue or some more questions?

**Comment by jedarden** [comment]
Figured it out. There's an env variable called `URL_PREFIX`
Example for review. 

```
version: '3'

services:
  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    container_name: rediscommander
    depends_on:
      - "redis"
    labels:
      traefik.enable: true
      traefik.http.routers.rediscommander.entrypoints: web
      traefik.http.routers.rediscommander.rule: (Host(`domain.com`)) && PathPrefix(`/redis`)
      traefik.http.routers.rediscommander.service: rediscommander_service
      traefik.http.routers.rediscommander.priority: 1000
      traefik.http.services.rediscommander_service.loadBalancer.server.port: 8080
      traefik.http.services.rediscommander_service.loadBalancer.server.scheme: http
      traefik.port: 8080
      traefik.docker.network: web
    environment:
      PORT: 8080
      HTTP_USER: [[user]]
      HTTP_PASSWORD: [[password]]
      URL_PREFIX: /redis

```
