### ISSUE TITLE
last version from dockerhub is broken ?

### ISSUE THREAD

**Issue by rafipiccolo** [joeferner/redis-commander#431]
hello,

I cant acces to rediscommander since the docker pull this morning. (i update once a day)

i use a compose file :
```
    redis:
        image: redis
        container_name: redis
        restart: always
        volumes:
            - ./redis/data:/data
        command: redis-server --save "" --appendonly no --latency-monitor-threshold 100
        healthcheck:
            test: ['CMD', 'bash', '-c', 'test $$(redis-cli ping) = PONG']

    rediscommander:
        container_name: rediscommander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        labels:
            - traefik.enable=true
            - traefik.http.routers.redis-commander.rule=Host(`rediscommander.${DOMAIN}`)
            - traefik.http.routers.redis-commander.tls.certresolver=le
            - traefik.http.routers.redis-commander.entrypoints=websecure
            - traefik.http.routers.redis-commander.middlewares=securityheaders,admin
```

docker inspect shows this since container update this morning :
```
# docker inspect rediscommander --format '{{ json .State }}' | jq
{
            "Start": "2020-12-20T15:03:40.550196273+01:00",
            "End": "2020-12-20T15:03:41.70911787+01:00",
            "ExitCode": 1,
            "Output": "Config key \"connections.0.port\" value (current: 6379) must be an integer number!\nConfiguration invalid - 1 errors found.\n"
          },
```

**Comment by sseide** [comment]
cannot reproduce - pulled last version and start withed docker from command line and its parsing REDIS_HOST correctly.$ 
```
docker run --name rc -e REDIS_HOSTS=local:redis:6379 rediscommander/redis-commander

Creating custom redis-commander config '/redis-commander/config/local-production.json'.
Parsing 1 REDIS_HOSTS into custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander 
Using scan instead of keys
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
setUpConnection (R:redis:6379:0) Redis error Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
```
For me the ENOTFOUND is normal as host name "redis" does not resolve here. But this is way after the config validation you get an error from. Therefor not stopping a parsing the port.

What are the full logs from start - the lines before the "Config key..." error message?

Did you tried to delete current image and pull it again?

**Comment by rafipiccolo** [comment]
Thanks for your time,
This is the log of the container, it looks good to me.

(i tried to rm and pull it again. same behavior)

```
today at 15:16  Creating custom redis-commander config '/redis-commander/config/local-production.json'.
today at 15:16  Parsing 1 REDIS_HOSTS into custom redis-commander config '/redis-commander/config/local-production.json'.
today at 15:16  node ./bin/redis-commander 
today at 15:16  Using scan instead of keys
today at 15:16  No Save: false
today at 15:16  listening on 0.0.0.0:8081
today at 15:16  access with browser at http://127.0.0.1:8081
today at 15:16  Redis Connection redis:6379 using Redis DB #0
```

the error i gave you come from the healthcheck defined in the original dockerfile

if i desactivate your healthcheck, he doesnt fail, ofc :).
and since it doenst fail, everything works as expected.
this is because when the healthcheck "fails", traefik doesnt reverse proxy to this container.

just to be clear, this is what i need to do for it to work. since this morning.
i think the bug appeared recently somewhere is healthcheck.js

```
rediscommander:
    ...
    healthcheck:
        disable: true
```
