### ISSUE TITLE
Issues connecting to a protected redis

### ISSUE THREAD

**Issue by remus-corneliu** [joeferner/redis-commander#433]
I have this simple docker-compose file. 

```
services:
  redis-dev-master: 
    build:
      context: .
      dockerfile: ./redis.master.dockerfile
    image: redis:master
    container_name: redis-dev-master
    networks:
      htss-local:
        ipv4_address: 192.168.0.7
    ports:
      - 10020:6379
    volumes:
      - redis-master-volume:/data
    restart: unless-stopped    
    command: "redis-server /config/redis.conf"

  redis-dev-slave-1: 
   build:
     context: .
     dockerfile: ./redis.slave.dockerfile
   image: redis:slave
   container_name: redis-dev-slave-1
   depends_on:
     - redis-dev-master
   networks:
     htss-local:
       ipv4_address: 192.168.0.8
   ports:
     - 10021:6379
   volumes:
     - redis-slave1-volume:/data
   restart: unless-stopped  
   command: "redis-server /config/redis.conf"

  redis-dev-slave-2: 
    build:
      context: .
      dockerfile: ./redis.slave.dockerfile
    image: redis:slave
    container_name: redis-dev-slave-2
    depends_on:
      - redis-dev-master
    networks:
      htss-local:
        ipv4_address: 192.168.0.9
    ports:
      - 10022:6379
    volumes:
      - redis-slave2-volume:/data
    restart: unless-stopped   
    command: "redis-server /config/redis.conf"
   
  redis-dev-sentinel-1: 
    build:
      context: .
      dockerfile: ./redis.sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-dev-sentinel-1
    networks:
      htss-local:
        ipv4_address: 192.168.0.10
    ports:
      - 10023:26379
    depends_on:
      - redis-dev-master
      - redis-dev-slave-1
      - redis-dev-slave-2
    volumes:
      - redis-sentinel1-volume:/data
    restart: unless-stopped    
    command: "redis-sentinel /config/redis.conf"
    
  redis-dev-sentinel-2: 
    build:
      context: .
      dockerfile: ./redis.sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-dev-sentinel-2
    networks:
      htss-local:
        ipv4_address: 192.168.0.11
    ports:
      - 10024:26379
    depends_on:
      - redis-dev-master
      - redis-dev-slave-1
      - redis-dev-slave-2
    volumes:
      - redis-sentinel2-volume:/data
    restart: unless-stopped    
    command: "redis-sentinel /config/redis.conf"
    
  redis-dev-sentinel-3: 
    build:
      context: .
      dockerfile: ./redis.sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-dev-sentinel-3
    networks:
      htss-local:
        ipv4_address: 192.168.0.12
    ports:
      - 10025:26379
    depends_on:
      - redis-dev-master
      - redis-dev-slave-1
      - redis-dev-slave-2
    volumes:
      - redis-sentinel3-volume:/data
    restart: unless-stopped    
    command: "redis-sentinel /config/redis.conf"

  redis-dev-ui:
    image: rediscommander/redis-commander:latest
    container_name: redis-dev-ui
    networks:
      htss-local:
        ipv4_address: 192.168.0.13
    ports:
    - 10026:8081
    depends_on:
      - redis-dev-master
    environment:
    - REDIS_HOSTS=local:redis-dev-master:6379
    - SENTINELS='redis-dev-sentinel-3:26379:redismaster,redis-dev-sentinel-2:26379:redismaster,redis-dev-sentinel-1:26379:redismaster'
    # - REDIS_PASSWORD=pass
    restart: unless-stopped    
```

Running this will result in this.

setUpConnection (S:redis-dev-sentinel-3:26379:mymaster-0) Redis error Error: All sentinels are unreachable. Retrying from scratch after 250ms. Last error: ERR No such master with that name redis-dev-ui at /redis-commander/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:3

Also, if I'm setting up a password for the redis, is going to complain about it and not be able to conenct to the redis server.

I've tried overriding the command section "redis-commander --redis-password ...." it complains about not knowing what ```redis-commander``` is 

Am I doing something wrong ? the base image for the redis is redis:6.0-alpine
