### ISSUE TITLE
docker ports doesn't propagate to configuration file

### ISSUE THREAD

**Issue by avico78** [joeferner/redis-commander#442]
as port 8081 as occupied by different docker ,
i tried to set other port ,
see docker compose:
```
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis_db:6379
    networks:
      - dockers_default
    ports:
    - "8083:8083"

```
but as check in logs , docker still listenning to 8081:
```

 # docker logs -f redis-commander
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander
Using scan instead of keys
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
````

as check it /redis-commander/config/default.json 
holds the port but it's set (hardcoded?) to 8081.
```
"server": {
    "address": "0.0.0.0",
    "port": 8081,
    "urlPrefix": "",
    "trustProxy": false,
    "clientMaxBodySize": "100kb",
    "httpAuth": {
      "username": "",
      "password": "",
      "passwordHash": "",
      "comment": "to enable http auth set username and either password or passwordHash",
      "jwtSecret": ""
    }
  }

```
After changing default.json -> port to 8083 i manage to access the web interface.
