### ISSUE TITLE
--redis-password  --env REDIS_PASSWORD= does not  work  

### ISSUE THREAD

**Issue by xiaozhitaba** [joeferner/redis-commander#444]
when  browse  http://ip:8081/  ERROR: Status: reconnecting

**Comment by SerhatTeker** [comment]
> `REDIS_PASSWORD` only works with SINGLE redis server defined via `REDIS_HOST` It does not set passwords for multiple servers defined via `REDIS_HOSTS` (plural)

Didn't know and couldn't find that. It fixed my problem. Thank you.

For future references I'm leaving the working example:

`compose-local.yml`

```yaml
version: "3.5"

services:
  redis:
    container_name: localredis
    hostname: localredis
    image: redis:6.2.5
    command: redis-server --requirepass pa$$w0rd
    ports:
      - "127.0.0.1:6379:6379"
    restart:
      unless-stopped
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOST=redis
    - REDIS_PASSWORD=pa$$w0rd
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart:
      unless-stopped
```
