### ISSUE TITLE
The secret reference does not seem to work.

### ISSUE THREAD

**Issue by espala** [joeferner/redis-commander#445]
Hello there,

I am installing the redis-commander tool with Kubernetes. But i have a problem. I'm keep my Redis password on a secret.yaml. It doesn't see when I add my password in secret.yaml file as reference environment. But when I type the password static, it works.

I used static and secret reference in different env names for testing. The container sees both environment values. I can print on the screen with the "echo" command.

I don't want to write my password directly to yaml file in a non-encrypted form. Do you have any suggestions for a solution to this?

My information;

**this scenario fails;**

all.yaml file;
```
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  namespace: redis-service
  labels:
    app.kubernetes.io/name: redis-commander
    app.kubernetes.io/component: redis-commander-service
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: redis-commander
    port: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: redis-commander-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis-service
  annotations:
    container.apparmor.security.beta.kubernetes.io/redis-commander: runtime/default
  labels:
    app.kubernetes.io/name: redis-commander-app
    app.kubernetes.io/component: redis-commander-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-commander-app
      app.kubernetes.io/component: redis-commander-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-commander-app
        app.kubernetes.io/component: redis-commander-app
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-cluster-service"
            - name: K8S_SIGTERM
              value: "1"
#            - name: REDIS_PASSWORD
#              value: "PasswordExample123"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-cluster-secret
                  key: auth
                  #optional: true
          ports:
            - name: redis-commander
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /favicon.png
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512M"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

```

error log;
```
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --redis-host redis-cluster-service --redis-password <set>   for k8s
Using scan instead of keys
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
setUpConnection (R:redis-cluster-service:6379:0) Redis error ReplyError: ERR invalid password
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14)
redis command "command" not supported, cannot build dynamic command list for (R:redis-cluster-service:6379:0
ReplyError: NOAUTH Authentication required.
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '0' ] }
}

```

**this scenario works;**
```
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  namespace: redis-service
  labels:
    app.kubernetes.io/name: redis-commander
    app.kubernetes.io/component: redis-commander-service
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: redis-commander
    port: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: redis-commander-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis-service
  annotations:
    container.apparmor.security.beta.kubernetes.io/redis-commander: runtime/default
  labels:
    app.kubernetes.io/name: redis-commander-app
    app.kubernetes.io/component: redis-commander-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-commander-app
      app.kubernetes.io/component: redis-commander-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-commander-app
        app.kubernetes.io/component: redis-commander-app
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-cluster-service"
            - name: K8S_SIGTERM
              value: "1"
            - name: REDIS_PASSWORD
              value: "PasswordExample123"
#            - name: REDIS_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                 name: redis-cluster-secret
#                  key: auth
                  #optional: true
          ports:
            - name: redis-commander
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /favicon.png
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512M"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

```

container logs;
```
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --redis-host redis-cluster-service --redis-password <set>  for k8s
Using scan instead of keys
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
Redis Connection redis-cluster-service:6379 using Redis DB #0
```

describe pod;
```
Name:         redis-commander-65bf455f5b-mdjqn
Namespace:    3party-applications
Priority:     0
Node:         kubernetes-cluster1-24fa18f6-lnhp/10.120.154.213
Start Time:   Thu, 20 May 2021 11:59:23 +0300
Labels:       app.kubernetes.io/component=redis-commander-app
              app.kubernetes.io/name=redis-commander-app
              pod-template-hash=65bf455f5b
Annotations:  <none>
Status:       Running
IP:           10.21.3.102
IPs:
  IP:           10.21.3.102
Controlled By:  ReplicaSet/redis-commander-65bf455f5b
Containers:
  redis-commander:
    Container ID:   docker://ed38ad88878e54d8059a9262fc1fefbacf8d37fe6382061f47f05e15d9dd1c23
    Image:          rediscommander/redis-commander:latest
    Image ID:       docker-pullable://rediscommander/redis-commander@sha256:0d4390823ead18f041ac6eca86318eac3c0558a215c82f3a9ffb39d7e2b73293
    Port:           8081/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 20 May 2021 11:59:24 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  512M
    Requests:
      cpu:     500m
      memory:  512M
    Liveness:  http-get http://:8081/favicon.png delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      REDIS_HOST:      redis-cluster-service
      K8S_SIGTERM:     1
      REDIS_PASSWORD:  PasswordExample123
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g8hq9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-g8hq9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-g8hq9
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  15s   default-scheduler  Successfully assigned 3party-applications/redis-commander-65bf455f5b-mdjqn to kubernetes-cluster1-24fa18f6-lnhp
  Normal  Pulling    14s   kubelet            Pulling image "rediscommander/redis-commander:latest"
  Normal  Pulled     14s   kubelet            Successfully pulled image "rediscommander/redis-commander:latest"
  Normal  Created    14s   kubelet            Created container redis-commander
  Normal  Started    14s   kubelet            Started container redis-commander

```

**For example when I give two environment values and check in container;**
yaml file;
```
...
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-cluster-service"
            - name: K8S_SIGTERM
              value: "1"
##########################################
            - name: REDIS_PASSWORD
              value: "PasswordExample123"
##########################################
            - name: REDIS_PASSWORD2
              valueFrom:
                secretKeyRef:
                  name: redis-cluster-secret
                  key: auth
                  #optional: true
##########################################
...
```

ssh into container;
kubectl exec -it redis-commander-d7fbbbc46-8dbsb sh
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
~ $ echo $REDIS_PASSWORD
PasswordExample123
~ $ echo $REDIS_PASSWORD1

~ $ echo $REDIS_PASSWORD2
PasswordExample123

```

I wrote the value "REDİS PASSWORD1" for testing with the echo command. Because there was no such value and it had to come blank. But the value "REDIS_PASSWORD2" answered me.
