### ISSUE TITLE
Redis error ClusterAllFailedError: Failed to refresh slots cache

### ISSUE THREAD

**Issue by gmussi** [joeferner/redis-commander#527]
I am facing an issue with the following `docker-compose.yml`:

```
  rediscmd:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOST: REDACTED.memorydb.eu-central-1.amazonaws.com
      REDIS_PORT: 6379
      REDIS_TLS: true
      REDIS_USERNAME: REDACTED
      REDIS_PASSWORD: REDACTED
```

It used to work fine before, but after pulling the latest image I am getting:

```
setUpConnection (C:REDACTED.memorydb.eu-central-1.amazonaws.com:6379:0) Redis error ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/redis-commander/node_modules/ioredis/built/cluster/index.js:308:31)
    at /redis-commander/node_modules/ioredis/built/cluster/index.js:325:21
    at Timeout.<anonymous> (/redis-commander/node_modules/ioredis/built/cluster/index.js:662:24)
    at Timeout.run (/redis-commander/node_modules/ioredis/built/utils/index.js:117:22)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7)
```

Without any changes in infrastructure or configuration.
