### ISSUE TITLE
docker compose in arm64 system fails with Error: Permission denied when no volume mounted, and when config folder mounted as volume: Configuration property "redis.defaultLabel" is not defined

### ISSUE THREAD

**Issue by nikhil-scholarlify** [joeferner/redis-commander#572]
Hi, I tried running redis commander in a docker-compose, here's the relevant docker-compose.yaml contents:

```
    redis_db:
        image: redis:6.2.5-alpine
        container_name: dev-redis_db
        restart: unless-stopped
        user: 1000:1000
        shm_size: '200mb'
        ports:
            - 5004:6379
        volumes:
            - ./persistent-data/redis:/data:rw

    redis-commander1:
        image: ghcr.io/joeferner/redis-commander:latest
        container_name: dev-redis-commander1
        restart: always
        user: 1000:1000
        ports:
            - "5005:8081"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
            - REDIS_HOSTS=local:redis_db:6379
        volumes:
            - ./persistent-data/redis:/redis-commander/config/:rw
```

(i couldn't tell whether REDIS_HOST & REDIS_PORT are required, or REDIS_HOSTS. so have set both in the hopes that it'll pickup something)

And it fails to start. Here are the logs:

```
dev-redis-commander1  | Node.js v18.20.1
dev-redis-commander1  | Creating custom redis-commander config '/redis-commander/config/local-production.json'.
dev-redis-commander1  | Parsing 1 REDIS_HOSTS into custom redis-commander config '/redis-commander/config/local-production.json'.
dev-redis-commander1  | node ./bin/redis-commander --redis-port 6379 --redis-host redis_db 
dev-redis-commander1  | /redis-commander/node_modules/config/lib/config.js:181
dev-redis-commander1  |     throw new Error('Configuration property "' + property + '" is not defined');
dev-redis-commander1  |     ^
dev-redis-commander1  | 
dev-redis-commander1  | Error: Configuration property "redis.defaultLabel" is not defined
dev-redis-commander1  |     at Config.get (/redis-commander/node_modules/config/lib/config.js:181:11)
dev-redis-commander1  |     at Object.<anonymous> (/redis-commander/bin/redis-commander.js:192:21)
dev-redis-commander1  |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
dev-redis-commander1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
dev-redis-commander1  |     at Module.load (node:internal/modules/cjs/loader:1203:32)
dev-redis-commander1  |     at Module._load (node:internal/modules/cjs/loader:1019:12)
dev-redis-commander1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
dev-redis-commander1  |     at node:internal/main/run_main_module:28:49
```

It creates a `local-production.json` in the persistent volume folder, here are its contents:
```
    {
    "connections": [
        {
            "label":"local",
            "host":"redis_db",
            "port":"6379",
            "password":"",
            "dbIndex":0
        }
    ]
    }
```

I'm not sure why it's looking for redis.defaultLabel and where to put it. Please help to get this to work.

Edit: FYI I'm on a cloud server under Hetzner with ARM64 type cpu, 8GB RAM, 4 vCPU . System info:
```
$ lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           Neoverse-N1
    Model:              1
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r3p1
    BogoMIPS:           50.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-3
Vulnerabilities:        
  Gather data sampling: Not affected
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec rstack overflow: Not affected
  Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Mitigation; CSV2, BHB
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

**Comment by nikhil-scholarlify** [comment]
just to clarify : on a different server that's on Amd64 / x-86 arch CPU, redis commander is working fine. Here's its docker compose yaml entry:
```
redis-commander1:
        image: rediscommander/redis-commander:latest
        container_name: dev-redis-commander1
        restart: always
        user: 1000:1000
        ports:
            - 8007:8081
        environment:
            - REDIS_HOST=redis-db
            - REDIS_PORT=6379
```
And I am able to access the aram64 server's redis db from this instance -- meaning my redis db itself is working fine.

**Comment by nikhil-scholarlify** [comment]
this seems to be the error-causing line: https://github.com/joeferner/redis-commander/blob/master/bin/redis-commander.js#L192
```
.options('redis-label', {
    type: 'string',
    describe: 'The label to display for the connection.',
    default: config.get('redis.defaultLabel')
  })
```

**Comment by sseide** [comment]
Than you have done something you should not do. The value is there:
https://github.com/joeferner/redis-commander/blob/deed27cc9af77fa3666fbbc3db7541fc9f62cac8/config/default.json#L21

As its written in the documentation - never ever change the "`default.json" file but add a new config file to overwrite the default values. Otherwise happens this...
Or more specifically - with your docker mount you have overwritten the entire config directory wiping out out booth necessary files (`default.json` and `custom-environment-variables.json` for env-var to config mapping).

You must only mount your new config file into docker and not the entire directory.

**Comment by nikhil-scholarlify** [comment]
@sseide i have simply run the docker-compose.yaml whose contents I have shared at the top here. I have not cloned this repo, not done any code editing at all, not built any docker image. I have used the docker image "ghcr.io/joeferner/redis-commander:latest" .

**Comment by nikhil-scholarlify** [comment]
@sseide this is what we get when there's nothing mounted:

docker-compose.yaml:
```
    redis-commander1:
        image: ghcr.io/joeferner/redis-commander:latest
        container_name: dev-redis-commander1
        restart: always
        user: 1000:1000
        ports:
            - "5005:8081"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
```
logs:
```
dev-redis-commander1  | Creating custom redis-commander config '/redis-commander/config/local-production.json'.
dev-redis-commander1  | /redis-commander/docker/entrypoint.sh: line 51: can't create /redis-commander/config/local-production.json: Permission denied
dev-redis-commander1  | /redis-commander/docker/entrypoint.sh: line 60: can't create /redis-commander/config/local-production.json: Permission denied
dev-redis-commander1  | jq: error: Could not open file config/custom-environment-variables.json: Permission denied
dev-redis-commander1  | ERROR: config file config/custom-environment-variables.json has invalid json syntax
```

**Comment by sseide** [comment]
what docker / podman / ... version do you use?

**Comment by nikhil-scholarlify** [comment]
```
$ docker -v
Docker version 24.0.7, build afdd53b
```

I tried now with the previously created `local-production.json` file mounted:
```
    redis-commander1:
        image: ghcr.io/joeferner/redis-commander:latest
        container_name: dev-redis-commander1
        restart: always
        user: 1000:1000
        ports:
            - "5005:8081"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
        volumes:
            - ./persistent-data/redis/local-production.json:/redis-commander/config/local-production.json:rw
```

and now getting the jq error:
```
dev-redis-commander1  | jq: error: Could not open file config/custom-environment-variables.json: Permission denied
dev-redis-commander1  | ERROR: config file config/custom-environment-variables.json has invalid json syntax
```

**Comment by nikhil-scholarlify** [comment]
@sseide I got it to work with this workaround:

- cloned this repo
- copied the config/ folder to my server
- mounted the copied-over config/ folder in the docker service onto /redis-commander/config path

Now redis commander is working fine.  
docker-compose.yaml:  
```
services:
    redis-commander1:
        image: ghcr.io/joeferner/redis-commander:latest
        container_name: dev-redis-commander1
        restart: always
        user: 1000:1000
        ports:
            - "5005:8081"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
        volumes:
            - ./persistent-data/redis/config:/redis-commander/config:rw
```
I'm now able to see redis commander on http://[server-IP]:5005 .

Looks like it needs couple of files from the repo to be mounted and present on paths `/redis-commander/config/custom-environment-variables.json` and  `/redis-commander/config/default.json` ; and afer that it needs adequate permissions to be able write to path `/redis-commander/config/local-production.json` to be able to run.

**Comment by sseide** [comment]
Sorry - seems there was a recent change in the docker-compose plugin done...
Compose changed the default user an image is run to something else. Did not found anything within the release-notes
up to now... And this "random(?)" user does not have the file access rights needed.

Please add the "user" directive to the redis-commander service and test if its working than.

```
services:
    redis-commander1:
      image: ghcr.io/joeferner/redis-commander:latest
      ...
      user: redis
```

For me its working than again.
Running directly with "docker" is working as expected, using "docker compose" with latest version gives your error.
